version: "3.3"
services:
  postgres:
    image: postgres:14
    healthcheck:
      test: "exit 0"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - .:/mnt

  backend:
    restart: unless-stopped
    depends_on:
      - postgres
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/code
      - static_volume:/code/static
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}

    #FOR SUPER USER CREATE (creatioion) - add the "python manage.py createsuperuser --no-input " this line down.
    command: bash -c "python manage.py makemigrations && python manage.py migrate --no-input && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:${BACKEND_PORT}"

  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:80" # host:container
    depends_on:
      - backend
    volumes:
      - static_volume:/code/static

volumes:
  pgdata:
  static_volume:
